- hosts: all
  vars:
    version: "{{ version }}"
  become: true
  tasks:
# ----------------------------INSTALL DB SERVER----------------------------------
    - name: Install MySQL Server on Ubuntu
      apt:
        name: mysql-server
        state: present
        update_cache: yes
# ----------------------------INSTALL SSM----------------------------------
    - name: Install dependencies
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download SSM Agent package
      get_url:
        url: https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/debian_amd64/amazon-ssm-agent.deb
        dest: /tmp/amazon-ssm-agent.deb

    - name: Install SSM Agent
      apt:
        deb: /tmp/amazon-ssm-agent.deb

    - name: Enable and start SSM Agent
      systemd:
        name: amazon-ssm-agent
        enabled: yes
        state: started
# ----------------------------INSTALL PRESTASHOP DB----------------------------------
    - name: Create PrestaShop database
      mysql_db:
        name: "storefront"
        state: present

    - name: Download PrestaShop
      get_url:
        url: "https://github.com/PrestaShop/PrestaShop/archive/refs/tags/{{ version }}.zip"
        dest: "/tmp/prestashop.zip"

    - name: Unzip PrestaShop
      unarchive:
        src: "/tmp/prestashop.zip"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set permissions
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        recurse: yes