- hosts: all
  vars:
    version: "{{ version }}"
  become: true
  tasks:
# ----------------------------INSTALL DB SERVER----------------------------------
    - name: Install MySQL Server on Ubuntu
      apt:
        name: mysql-server
        state: present
        update_cache: yes
# ----------------------------INSTALL SSM----------------------------------
    - name: Ensure snap is installed
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Ensure SSM Agent is installed via snap
      command: snap install amazon-ssm-agent --classic
      register: ssm_result
      changed_when: "'installed' in ssm_result.stdout or 'updated' in ssm_result.stdout"
      failed_when: false

    - name: Enable & start the SSM agent
      systemd:
        name: amazon-ssm-agent
        enabled: yes
        state: started
# ----------------------------INSTALL PRESTASHOP DB----------------------------------
    - name: Create PrestaShop database
      mysql_db:
        name: "storefront"
        state: present

    - name: Download PrestaShop
      get_url:
        url: "https://github.com/PrestaShop/PrestaShop/archive/refs/tags/{{ version }}.zip"
        dest: "/tmp/prestashop.zip"

    - name: Unzip PrestaShop
      unarchive:
        src: "/tmp/prestashop.zip"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set permissions
      file:
        path: /var/www/html/
        owner: www-data
        group: www-data
        recurse: yes