- hosts: all
  vars:
    version: "{{ version }}"
  become: true
  tasks:
# ----------------------------INSTALL WEB SERVER AND DEPENDENCIES----------------------------------
    - name: Ensure required packages are installed
      apt:
        name: [apache2, unzip, php, php-mysql, libapache2-mod-php, wget]
        state: present
        update_cache: yes
# ----------------------------INSTALL SSM----------------------------------
    - name: Install dependencies
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download SSM Agent package
      get_url:
        url: https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/debian_amd64/amazon-ssm-agent.deb
        dest: /tmp/amazon-ssm-agent.deb

    - name: Install SSM Agent
      apt:
        deb: /tmp/amazon-ssm-agent.deb

    - name: Enable and start SSM Agent
      systemd:
        name: amazon-ssm-agent
        enabled: yes
        state: started
# ----------------------------INSTALL PRESTASHOP WEB----------------------------------
    - name: Create website root directory
      file:
        path: "/var/www/storefront"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Download PrestaShop version {{ version }}
      get_url:
        url: "https://download.prestashop.com/download/releases/prestashop_{{ version }}.zip"
        dest: "/tmp/prestashop.zip"
        mode: '0644'

    - name: Unpack PrestaShop
      unarchive:
        src: "/tmp/prestashop.zip"
        dest: "/var/www/storefront"
        remote_src: yes

    - name: Set permissions
      file:
        path: "/var/www/storefront"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure Apache VirtualHost
      copy:
        dest: "/etc/apache2/sites-available/storefront.conf"
        content: |
          <VirtualHost *:80>
              ServerName storefront
              DocumentRoot /var/www/storefront
              <Directory /var/www/storefront>
                  AllowOverride All
                  Require all granted
              </Directory>
          </VirtualHost>

    - name: Enable site and rewrite module
      shell: |
        a2ensite storefront.conf
        a2enmod rewrite
        systemctl reload apache2
