---
- name: Install osCommerce and setup database
  hosts: all
  become: yes

  vars:
    OSCOMMERCE_VERSION: "oscommerce-4.13.1"
    OSCOMMERCE_ZIP: "{{ OSCOMMERCE_VERSION }}.zip"
    OSCOMMERCE_URL: "https://github.com/osCommerce/oscommerce/releases/download/v4.13.1/{{ OSCOMMERCE_ZIP }}"
    OSCOMMERCE_WEBROOT: "/var/www/html/oscommerce"

    MYSQL_ROOT_PASSWORD: "rootpass"
    OSCOMMERCE_DB_NAME: "oscommerce_db"
    OSCOMMERCE_DB_USER: "oscuser"
    OSCOMMERCE_DB_PASSWORD: "oscpass"
    DB_LOGIN_SOCKET: "/var/run/mysqld/mysqld.sock"

  tasks:
  - name: Install required packages
    apt:
      name:
        - apache2
        - php
        - php-mysql
        - unzip
        - mariadb-server
        - python3-pymysql
      state: present
      update_cache: yes

  - name: Ensure Apache and DB services are running
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - apache2
      - mariadb

  - name: Set MySQL root password
    command: >
      mysqladmin -u root password {{ MYSQL_ROOT_PASSWORD }}
    changed_when: true
    ignore_errors: true

  - name: Create osCommerce database
    community.mysql.mysql_db:
      name: "{{ OSCOMMERCE_DB_NAME }}"
      state: present
      login_user: root
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"

  - name: Create osCommerce DB user
    community.mysql.mysql_user:
      name: "{{ OSCOMMERCE_DB_USER }}"
      password: "{{ OSCOMMERCE_DB_PASSWORD }}"
      priv: "{{ OSCOMMERCE_DB_NAME }}.*:ALL"
      state: present
      host: "localhost"
      login_user: root
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"

  - name: Create web root directory
    file:
      path: "{{ OSCOMMERCE_WEBROOT }}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'

  - name: Download osCommerce
    get_url:
      url: "{{ OSCOMMERCE_URL }}"
      dest: "/tmp/{{ OSCOMMERCE_ZIP }}"
      mode: '0644'

  - name: Extract osCommerce
    unarchive:
      src: "/tmp/{{ OSCOMMERCE_ZIP }}"
      dest: "{{ OSCOMMERCE_WEBROOT }}"
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Set permissions
    file:
      path: "{{ OSCOMMERCE_WEBROOT }}"
      owner: www-data
      group: www-data
      recurse: yes
