name: Test Pipeline

on:
  workflow_call:
  push:
    branches: [ "test" ]

permissions:
  id-token: write
  contents: read

# env:
#   VERSION: "8.2.1" # 1.7.8.11/8.2.1 

jobs:
  create-eks-monitoring-cluster:
    name: Setup eks-monitoring Grafana/Prometheus
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_PIPELINE_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform Init and Apply
      run: |
        terraform -chdir=eks-monitoring init
        terraform -chdir=eks-monitoring plan -lock=false -out=plan.tfplan \
          -var="cluster_name=$EKS_CLUSTER_NAME" \
          -var="pipeline_role_arn=$AWS_PIPELINE_ROLE" 
        terraform apply -lock=false -auto-approve plan.tfplan
      env:
        EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        AWS_PIPELINE_ROLE: ${{ secrets.AWS_PIPELINE_ROLE }}



    - name: Show Grafana Hostname
      run: |
        terraform -chdir=eks-monitoring output -raw grafana_service_hostname || true

