name: Create & deploy Storefront infrastructure

on:
  push:
    branches: [ "test" ]

permissions:
  id-token: write
  contents: read

jobs:

# -------------------------------------------------------------------------------------------
  create-golden-image:
    name: Create base image
    runs-on: ubuntu-latest
    environment: Prod
    outputs:
      base_ami_id: "ami-0caf48451cb6750de"
      base_ami_name: "snapshot-storefront-base-v20250526.1"
      base_ami_namepart: "v20250526.1"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

# -------------------------------------------------------------------------------------------
  test-base-image:
    name: Test base image
    needs: create-golden-image
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display AMI name part
      run: |
        echo "Using AMI name part: ${{ needs.create-golden-image.outputs.base_ami_namepart }}"

# -------------------------------------------------------------------------------------------
  create-role-image:
    name: Create and customize role images
    needs: test-base-image
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Launch DB EC2 instance from AMI
      id: db_ec2_launch
      run: |
        NAME="ec2-db-zero-storefront-${{ needs.create-golden-image.outputs.base_ami_namepart }}"
        echo "Launching instance named $NAME"
